# Generated by Django 4.1.6 on 2023-03-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_book_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.CharField(max_length=100, null=True, verbose_name="pages"),
        ),
    ]
